on: push
name: 🚀 Deploy Rida-boys-school on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.biztechsols.co.uk
        username: biztechsols.co.uk
        password: 7ba35455b2a5
        server-dir: ./rida-boys-school/